databases:
  - name: doctors_appointment_back_end
    databaseName: doctors_appointment_back_end
    user: mysite

services:
  - type: web
    name: doctors_appointment_back_end
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: doctors_appointment_back_end
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false