---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/appointments":
    get:
      summary: list appointments
      responses:
        '200':
          description: successful
    post:
      summary: create appointment
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                city:
                  type: string
                appointment_time:
                  type: string
                  format: date-time
                user_id:
                  type: integer
                doctor_id:
                  type: integer
              required:
              - city
              - apppointment_time
              - user_id
              - doctor_id
  "/api/v1/appointments/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    delete:
      summary: delete appointment
      responses:
        '200':
          description: Appointment created successfully!
  "/api/v1/doctors":
    get:
      summary: list doctors
      responses:
        '200':
          description: All doctors loaded successfully!
    post:
      summary: create doctor
      parameters: []
      responses:
        '201':
          description: Doctor created successfully!
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                fee:
                  type: integer
                image:
                  type: string
                details:
                  type: string
              required:
              - name
              - fee
              - image
              - details
  "/api/v1/doctors/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show doctor
      responses:
        '200':
          description: Doctor loaded successfully!
    delete:
      summary: delete doctor
      responses:
        '200':
          description: Doctor deleted successfully
  "/api/login":
    post:
      summary: login user
      parameters: []
      responses:
        '200':
          description: Logged in successfully!!
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/api/register":
    post:
      summary: signup user
      parameters: []
      responses:
        '201':
          description: Successfully signed up!!
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
              required:
              - name
              - email
              - password
              - password_confirmation
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3001/
